from django.urls import path

from .views import (
    ActivityHistoryAPIView,
    ActivityListAPIView,
    DashboardAPIView,
    DashboardRecentActivityAPIView,
    DashboardRecentEnquiriesAPIView,
    EnquiryDetailAPIView,
    EnquiryListCreateAPIView,
    InvoiceAPIView,
    InvoiceAttachmentAPIView,
    InvoiceAttachmentDownloadAPIView,
    OrderAPIView,
    OrderAttachmentAPIView,
    OrderAttachmentDownloadAPIView,
    QuotationAPIView,
    QuotationAttachmentAPIView,
    QuotationAttachmentDownloadAPIView,
    RequirementsAPIView,
)

urlpatterns = [
    path("dashboard/", DashboardAPIView.as_view(), name="enquiry-dashboard"),
    path("dashboard/recent-enquiries/", DashboardRecentEnquiriesAPIView.as_view(), name="enquiry-dashboard-recent-enquiries"),
    path("dashboard/recent-activity/", DashboardRecentActivityAPIView.as_view(), name="enquiry-dashboard-recent-activity"),
    path("activity/", ActivityHistoryAPIView.as_view(), name="enquiry-activity-history"),
    path("", EnquiryListCreateAPIView.as_view(), name="enquiry-list-create"),
    path("<int:pk>/", EnquiryDetailAPIView.as_view(), name="enquiry-detail"),
    path("<int:pk>/requirements/", RequirementsAPIView.as_view(), name="enquiry-requirements"),
    path("<int:pk>/quotation/", QuotationAPIView.as_view(), name="enquiry-quotation"),
    path("<int:pk>/quotation/attachment/", QuotationAttachmentAPIView.as_view(), name="enquiry-quotation-attachment"),
    path("<int:pk>/quotation/attachment/download/", QuotationAttachmentDownloadAPIView.as_view(), name="enquiry-quotation-attachment-download"),
    path("<int:pk>/order/", OrderAPIView.as_view(), name="enquiry-order"),
    path("<int:pk>/order/attachment/", OrderAttachmentAPIView.as_view(), name="enquiry-order-attachment"),
    path("<int:pk>/order/attachment/download/", OrderAttachmentDownloadAPIView.as_view(), name="enquiry-order-attachment-download"),
    path("<int:pk>/invoice/", InvoiceAPIView.as_view(), name="enquiry-invoice"),
    path("<int:pk>/invoice/attachment/", InvoiceAttachmentAPIView.as_view(), name="enquiry-invoice-attachment"),
    path("<int:pk>/invoice/attachment/download/", InvoiceAttachmentDownloadAPIView.as_view(), name="enquiry-invoice-attachment-download"),
    path("<int:pk>/activity/", ActivityListAPIView.as_view(), name="enquiry-activity"),
]
