# Generated by Django 5.0.6 on 2026-08-14 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=30, unique=True)),
                ("last_number", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Enquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enquiry_number",
                    models.CharField(
                        db_index=True, editable=False, max_length=20, unique=True
                    ),
                ),
                ("enquiry_date", models.DateField(db_index=True)),
                (
                    "business_line",
                    models.CharField(
                        choices=[
                            ("Laptop Sales", "Laptop Sales"),
                            ("Desktop Sales", "Desktop Sales"),
                            ("Networking", "Networking"),
                            ("CCTV", "CCTV"),
                            ("Software Services", "Software Services"),
                            ("Cloud Services", "Cloud Services"),
                            ("AMC", "AMC"),
                            ("IT Support", "IT Support"),
                            ("Hardware", "Hardware"),
                            ("Cyber Security", "Cyber Security"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "enquiry_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Website", "Website"),
                            ("Referral", "Referral"),
                            ("Cold Call", "Cold Call"),
                            ("Email", "Email"),
                            ("Phone", "Phone"),
                            ("Walk-in", "Walk-in"),
                            ("Existing Client", "Existing Client"),
                            ("Exhibition", "Exhibition"),
                            ("Social Media", "Social Media"),
                            ("Other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("High", "High"),
                            ("Urgent", "Urgent"),
                        ],
                        default="Medium",
                        max_length=10,
                    ),
                ),
                ("sales_person", models.CharField(blank=True, max_length=150)),
                ("expected_closing_date", models.DateField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("New", "New"),
                            ("In Progress", "In Progress"),
                            ("Quotation Prepared", "Quotation Prepared"),
                            ("Quotation Shared", "Quotation Shared"),
                            ("Negotiation", "Negotiation"),
                            ("Won", "Won"),
                            ("Lost", "Lost"),
                            ("Cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="New",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enquiries_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enquiries",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Enquiries",
                "ordering": ["-enquiry_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enquiry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="enquiries.enquiry",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Activities",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(blank=True, max_length=30, null=True, unique=True),
                ),
                ("invoice_date", models.DateField(blank=True, null=True)),
                (
                    "value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Not Generated", "Not Generated"),
                            ("Draft", "Draft"),
                            ("Generated", "Generated"),
                            ("Sent", "Sent"),
                            ("Cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="Not Generated",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("Not Paid", "Not Paid"),
                            ("Partially Paid", "Partially Paid"),
                            ("Paid", "Paid"),
                            ("Overdue", "Overdue"),
                        ],
                        db_index=True,
                        default="Not Paid",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("payment_date", models.DateField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True)),
                (
                    "enquiry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice",
                        to="enquiries.enquiry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(blank=True, max_length=30, null=True, unique=True),
                ),
                ("order_date", models.DateField(blank=True, null=True)),
                ("po_number", models.CharField(blank=True, max_length=100)),
                ("po_date", models.DateField(blank=True, null=True)),
                (
                    "value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Not Converted", "Not Converted"),
                            ("Pending", "Pending"),
                            ("Confirmed", "Confirmed"),
                            ("Partially Confirmed", "Partially Confirmed"),
                            ("Cancelled", "Cancelled"),
                            ("Completed", "Completed"),
                        ],
                        db_index=True,
                        default="Not Converted",
                        max_length=25,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                (
                    "enquiry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order",
                        to="enquiries.enquiry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Quotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quotation_number",
                    models.CharField(blank=True, max_length=30, null=True, unique=True),
                ),
                ("quotation_date", models.DateField(blank=True, null=True)),
                (
                    "value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("valid_until", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Not Prepared", "Not Prepared"),
                            ("Draft", "Draft"),
                            ("Prepared", "Prepared"),
                            ("Shared", "Shared"),
                            ("Accepted", "Accepted"),
                            ("Rejected", "Rejected"),
                            ("Expired", "Expired"),
                        ],
                        db_index=True,
                        default="Not Prepared",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                (
                    "enquiry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotation",
                        to="enquiries.enquiry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Requirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.CharField(max_length=255)),
                ("description", models.CharField(blank=True, max_length=500)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("Nos", "Nos"),
                            ("Set", "Set"),
                            ("Box", "Box"),
                            ("License", "License"),
                            ("Service", "Service"),
                            ("Meter", "Meter"),
                        ],
                        default="Nos",
                        max_length=20,
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "enquiry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="enquiries.enquiry",
                    ),
                ),
            ],
        ),
    ]
