# Generated by Django 5.0.6 on 2026-08-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enquiries", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotation",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="quotations/%Y/%m/"
            ),
        ),
        migrations.AlterField(
            model_name="enquiry",
            name="business_line",
            field=models.CharField(
                choices=[
                    ("Laptop Sales", "Laptop Sales"),
                    ("Desktop Sales", "Desktop Sales"),
                    ("Networking", "Networking"),
                    ("CCTV", "CCTV"),
                    ("Software Services", "Software Services"),
                    ("Cloud Services", "Cloud Services"),
                    ("AMC", "AMC"),
                    ("IT Support", "IT Support"),
                    ("Hardware", "Hardware"),
                    ("Cyber Security", "Cyber Security"),
                    ("Other", "Other"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
