# Generated by Django 5.0.6 on 2026-08-18 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enquiries", "0003_remove_quotation_attachment_quotationattachment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quotationattachment",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="quotationattachment",
            name="enquiries_q_quotati_c33b5e_idx",
        ),
        migrations.AddField(
            model_name="quotation",
            name="quotation_shared",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="quotationattachment",
            name="quotation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachment",
                to="enquiries.quotation",
            ),
        ),
    ]
