# Generated by Django 5.0.6 on 2026-08-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enquiries", "0005_order_expected_delivery_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="quotation_number",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
