# Generated by Django 5.0.6 on 2026-08-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enquiries", "0006_alter_invoice_invoice_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="po_number",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="quotation_number",
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
