# Generated by Django 6.0.7 on 2026-08-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enquiries", "0007_alter_invoice_invoice_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="amount_paid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
