# Generated by Django 5.0.6 on 2026-08-14 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_number", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_code",
                    models.CharField(
                        db_index=True, editable=False, max_length=20, unique=True
                    ),
                ),
                ("company_name", models.CharField(db_index=True, max_length=255)),
                (
                    "gst_number",
                    models.CharField(blank=True, db_index=True, max_length=15),
                ),
                ("pan_number", models.CharField(blank=True, max_length=10)),
                (
                    "company_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Private Limited", "Private Limited"),
                            ("Public Limited", "Public Limited"),
                            ("Partnership", "Partnership"),
                            ("Proprietorship", "Proprietorship"),
                            ("LLP", "LLP"),
                            ("Government", "Government"),
                            ("Other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("website", models.CharField(blank=True, max_length=255)),
                ("contact_person", models.CharField(max_length=150)),
                ("designation", models.CharField(blank=True, max_length=100)),
                ("mobile", models.CharField(db_index=True, max_length=15)),
                ("alternate_mobile", models.CharField(blank=True, max_length=15)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("alternate_email", models.EmailField(blank=True, max_length=254)),
                ("address_line_1", models.CharField(blank=True, max_length=255)),
                ("address_line_2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, db_index=True, max_length=100)),
                ("state", models.CharField(blank=True, db_index=True, max_length=100)),
                ("country", models.CharField(default="India", max_length=100)),
                ("pincode", models.CharField(blank=True, max_length=10)),
                (
                    "customer_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Corporate", "Corporate"),
                            ("Enterprise", "Enterprise"),
                            ("Government", "Government"),
                            ("SME", "SME"),
                            ("Individual", "Individual"),
                            ("Reseller", "Reseller"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("IT & Software", "IT & Software"),
                            ("Manufacturing", "Manufacturing"),
                            ("Healthcare", "Healthcare"),
                            ("Education", "Education"),
                            ("BFSI", "BFSI"),
                            ("Retail", "Retail"),
                            ("Logistics", "Logistics"),
                            ("Government", "Government"),
                            ("Real Estate", "Real Estate"),
                            ("Hospitality", "Hospitality"),
                        ],
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customers_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
