# Generated by Django 5.0.6 on 2026-08-18 10:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_alter_customer_address_line_1_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("pan_number", ""), _negated=True),
                fields=("pan_number",),
                name="unique_pan_number_when_set",
            ),
        ),
    ]
